# Generated by Django 4.0.3 on 2022-03-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('chat_app', '0002_room_count_ownroomlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaveAGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='count',
        ),
        migrations.AddField(
            model_name='room',
            name='member_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OwnRoomList',
        ),
        migrations.AddField(
            model_name='haveagroup',
            name='room_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat_app.room'),
        ),
        migrations.AddField(
            model_name='haveagroup',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
