# Generated by Django 4.0.3 on 2022-03-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('chat_app', '0003_haveagroup_remove_room_count_room_member_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='token',
            field=models.ManyToManyField(to='authtoken.token'),
        ),
        migrations.DeleteModel(
            name='HaveAGroup',
        ),
    ]
