# Generated by Django 4.0.3 on 2022-03-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('chat_app', '0004_room_token_delete_haveagroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='room',
            name='token',
        ),
        migrations.CreateModel(
            name='HaveAChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=50)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
        ),
    ]
